name: Update onlishop/platform package
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "onlishop/administration/**"
            - "onlishop/core/**"
            - "onlishop/storefront/**"
            - "onlishop/elasticsearch/**"

permissions:
    id-token: write

jobs:
    platform-sync:
        runs-on: ubuntu-latest
        concurrency: platform-sync-${{ github.ref }}
        name: Sync files for onlishop/platform package
        steps:
            - uses: octo-sts/action@main
              id: octo-sts
              with:
                scope: onlishop/recipes
                identity: PlatformSync
            - name: Clone
              uses: actions/checkout@v4
              with:
                token: ${{ steps.octo-sts.outputs.token }}

            - name: Sync files
              run: php .github/sync-platform.php

            - name: Add files to git
              run: git add .

            - name: Update onlishop/platform package
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: 'chore: update onlishop/platform package'
